# ADN run configs. Any settings added to this file will override the default configs
spineweb:
  train:
    batch_size: 2
    dataset_type: spineweb
  test:
    batch_size: 8
    dataset_type: spineweb
    a_dir: data/spineweb/test/artifact
    b_dir: data/spineweb/test/no_artifact
    random_flip: False
    metrics_step: .inf
deep_lesion:
  train:
    batch_size: 2
    dataset_type: deep_lesion
  test:
    batch_size: 8
    dataset_type: deep_lesion
    dataset_dir: data/deep_lesion/test
    partial_holdout: 0.0
    random_mask: False
    random_flip: False
    load_mask: True
nature_image:
  train:
    batch_size: 2
    input_ch: 3
    input_nc: 3
    dataset_type: nature_image
    a_dir: "data/nature_image/train/artifact"  # path to your train artifact dataset
    b_dir: "data/nature_image/train/no_artifact" # path to your train no_artifact dataset
  test:
    batch_size: 1
    input_ch: 3
    input_nc: 3
    dataset_type: nature_image
    a_dir: "data/nature_image/test/artifact" # path to your test artifact dataset
    b_dir: "data/nature_image/test/no_artifact" # path to your test no_artifact dataset
    random_flip: False
    crop_type: center
    metrics_step: .inf
